    version: '3.8'
         
    services:
      mongodb:
        image: mongo:6.0.6        
        environment:
          MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
          MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        volumes:
          - ./mongo-data:/data/db
        ports:
          - 27017:27017
     
      postgresdb: 
        image: postgres:15.3     
        environment:
          POSTGRES_USER: ${POSTGRES_USERNAME}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
        ports:
          - 5432:5432